os: linux
dist: trusty
language: php

#php:
#  - 5.6
#  - 7.2
##  - master

matrix:
  include:
    - dist: precise
      php: 5.3
      before_install:
        - pecl install redis
        - composer require phpunit/phpunit:^4

sudo: false
notifications:
  email: false

install:
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

#addons:
#  apt:
#    packages:
#      - libxml2-utils
#
#php:
#  - 7.1
#  - 7.2
#  - master
#
#matrix:
#  allow_failures:
#    - php: master
#  fast_finish: true
#
#env:
#  matrix:
#    - DEPENDENCIES="high"
#    - DEPENDENCIES="low"
#  global:
#    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"
#
#before_install:
#  - ./build/tools/composer clear-cache
#
#install:
#  - if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry ./build/tools/composer update $DEFAULT_COMPOSER_FLAGS; fi
#  - if [[ "$DEPENDENCIES" = 'low' ]]; then travis_retry ./build/tools/composer update $DEFAULT_COMPOSER_FLAGS --prefer-lowest; fi
#
#before_script:
#  - echo 'zend.assertions=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
#  - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
#
#script:
#  - ./phpunit --coverage-clover=coverage.xml
#
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
#
#notifications:
#  email: false
#
#jobs:
#  include:
#    - stage: Static Code Analysis
#      php: 7.2
#      env: PHPStan
#      before_install:
#        - travis_retry ./build/tools/composer require --no-update phpunit/php-invoker:^2.0
#      install: travis_retry ./build/tools/composer update --prefer-dist --prefer-stable
#      script:
#        - ./build/tools/phpstan analyse --level=0 -c phpstan.neon src
#        - ./build/tools/phpstan analyse --level=2 -c phpstan-tests.neon tests
#    - stage: Static Code Analysis
#      php: 7.2
#      env: php-cs-fixer
#      install:
#        - phpenv config-rm xdebug.ini
#      script:
#        - ./build/tools/php-cs-fixer fix --dry-run -v --show-progress=dots --diff-format=udiff
